### ISSUE TITLE
ROFL: Add a command to show ROFL staking requirements for a specific ParaTime

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/cli#290]
Currently the `network show native-token` output looks like
```
$ oasis net show native-token --network testnet
Network:                  testnet
Token's ticker symbol:    TEST
Token's base-10 exponent: 9
Total supply:             9999999997.0 TEST
Common pool:              1386172230.297244237 TEST
Last block fees:          0.0 TEST
Governance deposits:      0.0 TEST
Debonding interval:       336 epoch(s)

=== STAKING THRESHOLDS ===
  entity:             100.0 TEST
  node-validator:     100.0 TEST
  node-compute:       100.0 TEST
  node-keymanager:    100.0 TEST
  runtime-compute:    10000.0 TEST
  runtime-keymanager: 10000.0 TEST
```

Add a command (`oasis paratime show parameters` ?) to retrieve the stake requriements to create a ROFL app. Use the new `rofl.StakeThresholds` call introduced in https://github.com/oasisprotocol/oasis-sdk/issues/1993.

**Comment by kostko** [comment]
Not sure if this should go under "network" as that is used for the consensus layer?

In any case the `rofl` module first needs a query that would return this information so please also open an issue in the SDK and link it here.

**Comment by matevz** [comment]
> In any case the `rofl` module first needs a query that would return this information so please also open an issue in the SDK and link it here.

Should this also be updated in the [genesis document](https://docs.oasis.io/node/genesis-doc#staking-thresholds) page?

**Comment by kostko** [comment]
No, the genesis document is for the consensus layer.
