### ISSUE TITLE
Add support for sr25519 accounts

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/cli#35]
Oasis CLI currently supports ed25519 and secp256k1 wallets. Add suport for sr25519 as well. Also test, if signing with Ledger works (implemented in #11).

**Comment by matevz** [comment]
I did some research today how Polkadot uses sr25519.

Key derivation:
- they do not use standard bip32 derivation, but their own [*substrate* derivation](https://wiki.polkadot.network/docs/learn-account-advanced#derivation-paths) obtaining "soft" and "hard" keys.
- I tested [Enkrypt](https://www.enkrypt.com/) and [Polkagate](https://polkagate.xyz/) wallets and they derive the same substrate addresses for the given mnemonic.
- Ledger's Polkadot nano app (developed by Zondax) do not implement substrate, but a [bip44-like derivation](https://support.ledger.com/hc/en-us/sections/4404370208273-Polkadot-DOT-) using `m/44'/354'/account'/0'/0'` path. This gives incompatible addresses with Enkrypt and Polkagate.
- Importing Polkadot accounts is done via .json files or the mnemonic. No "Enter private key:" fields exist in the wallets.

Addresses:
- Polkadot addresses use Base58 encoding.
- Three types of addresses based on the prefix: Polkadot (0), Kusama (2) and Generic Substrate (42).

For better interoperability with Polkadot, I suggest we split the sr25519 work into:
- use Polkadot derivation path library (and add new account type `sr25519-substrate`?)
- use the ledger's way of deriving the account (PR #76, `sr25519-bip44`?)
- define Polkadot -> Oasis address mapping (similar to what we did for [ethereum](https://github.com/oasisprotocol/oasis-sdk/blob/c36a7ee194abf4ca28fdac0edbefe3843b39bf69/client-sdk/go/types/address.go#L135-L142))
- show sr25519 addresses in Polkadot's Base58 format
- support importing Polkadot wallets from JSON-encoded export file (I think this eventually generates `sr25519-substrate` type then)

**Comment by kostko** [comment]
I wouldn't support any of the interoperability stuff for now as there does not seem to be a clear use case. Implementing only the simplest correct scheme (compatible with Ledger) for now makes the most sense.

**Comment by matevz** [comment]
Implemented in https://github.com/oasisprotocol/cli/pull/119
