### ISSUE TITLE
Wrong warning for consensus transfer txes

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/cli#63]
Running the following

```
oasis account transfer 1.0 test:bob --account test:alice --network testnet  --no-paratime
```

the safety check complains about the invalid recepient:

```
Error: signer for address '0x0000000000000000000000000000000000000000' will not be able to sign transactions on consensus layer
Use --force to ignore this check
```

This is a perfectly valid transaction though.

**Comment by pro-wh** [comment]
> This is a perfectly valid transaction though.

clarification: valid command, bad transaction generated, correct error regarding that transaction

**Comment by pro-wh** [comment]
or no, is it?

**Comment by matevz** [comment]
Transaction was fine, because the native address is used there directly (`ResolveAddress` in SDK returns the native address + optionally ethereum address).

**Comment by pro-wh** [comment]
oh interesting
